In [1]:
import torch
import torchvision

torch.cuda.is_available()

True

In [2]:
x = torch.ones(3,3, dtype=torch.int)
x

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [3]:
x.size()

torch.Size([3, 3])

In [4]:
x = torch.tensor([2.5,0,1])
x

tensor([2.5000, 0.0000, 1.0000])

In [5]:
x = torch.rand(2,2)
y = torch.rand(2,2)
z = x + y
z

tensor([[1.2465, 0.3858],
        [0.8335, 0.9992]])

In [6]:
y.add_(x)
y

tensor([[1.2465, 0.3858],
        [0.8335, 0.9992]])

In [7]:
x = torch.rand(5,3)
x

tensor([[0.3673, 0.8106, 0.7595],
        [0.2801, 0.1533, 0.4206],
        [0.4472, 0.0415, 0.4963],
        [0.4238, 0.1852, 0.1501],
        [0.5872, 0.0837, 0.0669]])

In [8]:
print(x[:,0])

tensor([0.3673, 0.2801, 0.4472, 0.4238, 0.5872])


In [9]:
y = x.view(3,5)
y

tensor([[0.3673, 0.8106, 0.7595, 0.2801, 0.1533],
        [0.4206, 0.4472, 0.0415, 0.4963, 0.4238],
        [0.1852, 0.1501, 0.5872, 0.0837, 0.0669]])

In [10]:
import numpy as np

In [11]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [12]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [13]:
c = torch.from_numpy(b)
c

tensor([1., 1., 1., 1., 1.])

In [14]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5,device=device)
    y = torch.ones(5,device=device)
    z = x + y
    print(z)

tensor([2., 2., 2., 2., 2.], device='cuda:0')


In [15]:
x = torch.randn(3, requires_grad=True)
x

tensor([-0.9651, -0.3956, -0.3494], requires_grad=True)

In [16]:
y = x+2
y

tensor([1.0349, 1.6044, 1.6506], grad_fn=<AddBackward0>)

In [17]:
z = y*y*2
z

tensor([2.1419, 5.1480, 5.4491], grad_fn=<MulBackward0>)

In [18]:
z = z.mean()

In [19]:
z.backward() #dz/dx
print(x.grad)

tensor([1.3798, 2.1392, 2.2008])


In [20]:
weights = torch.ones(4, requires_grad = True)

for epoch in range(3):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)
    
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [23]:
import torch

x = torch.tensor(1.0)
y = torch.tensor(2.0)

w = torch.tensor(1.0, requires_grad=True)

In [25]:
#forward pass and compute loss

y_hat = w * x
loss = (y_hat-y)**2

loss

tensor(1., grad_fn=<PowBackward0>)

In [26]:
#backward pass

loss.backward()

w.grad

tensor(-2.)