# MSE LOSS

### Using torch

In [1]:
import torch
import torch.nn as nn

print(torch.cuda.is_available())

True


In [2]:
prediction = torch.randn(4,5)
prediction

tensor([[ 0.7952,  0.1419,  0.3281, -0.1781,  0.5669],
        [-1.1725,  0.3707, -1.4892,  0.2406,  0.8538],
        [-0.4485,  1.4588, -0.3751,  1.2651,  0.0466],
        [ 0.7564, -0.0640, -1.0265,  0.6220,  0.5277]])

In [3]:
label = torch.randn(4,5)
label

tensor([[ 0.6273,  0.2236,  0.1510,  0.4271,  0.0852],
        [ 0.2026, -0.3666, -0.9561, -0.3828, -0.1672],
        [-0.3047, -1.0763, -0.0252, -0.1805,  0.2118],
        [-0.1181, -1.5907, -0.0306,  1.2357,  0.1331]])

In [4]:
mse = nn.MSELoss(reduction='mean')
loss = mse(prediction,label)
loss

tensor(0.9061)

### No torch

In [5]:
mse_2 = ((label-prediction)**2).mean()
mse_2

tensor(0.9061)

# Binary Cross-entropy loss

### Using torch

In [6]:
prediction = torch.randn(4,5)
prediction

tensor([[ 1.6194e+00, -1.8278e+00,  8.5772e-01,  1.4382e+00,  1.3110e+00],
        [ 6.3131e-01,  9.9555e-03,  8.6269e-01,  1.2368e-01,  8.5791e-01],
        [-1.0380e+00, -5.3850e-01, -1.3660e+00,  6.1362e-01,  6.5805e-01],
        [ 8.9559e-04,  1.4919e-01,  3.2823e-01, -1.4508e+00,  9.5693e-02]])

In [7]:
labels = torch.zeros(4,5).random_(0,2)
labels

tensor([[0., 1., 1., 0., 1.],
        [1., 0., 1., 1., 0.],
        [0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 0.]])

In [8]:
sigmoid = nn.Sigmoid()

In [9]:
bce_loss = nn.BCELoss(reduction='mean')

In [10]:
loss = bce_loss(sigmoid(prediction),label)
loss

tensor(0.9099)

In [11]:
# with logits

bce_logits = nn.BCEWithLogitsLoss(reduction='mean')
loss = bce_logits(prediction,labels)                          #no need for sigmoid
loss

tensor(0.8277)

### no torch

In [12]:
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))

x = prediction.numpy()
x = sigmoid(x)

y = label.numpy()

In [13]:
x

array([[0.83471876, 0.13850248, 0.70218503, 0.80817556, 0.78768194],
       [0.6527871 , 0.50248885, 0.7032232 , 0.53087986, 0.70222396],
       [0.26154312, 0.36853635, 0.20326927, 0.64876693, 0.65882146],
       [0.5002239 , 0.5372296 , 0.58132946, 0.18987525, 0.5239051 ]],
      dtype=float32)

In [14]:
loss_values = []

for i in range(len(y)):
    
    batch_loss = []
    
    for j in range(len(y[0])):
        
        if y[i][j] == 1:
            loss = -np.log(x[i][j])
            
        else:
            loss = -np.log(1-x[i][j])
            
        batch_loss.append(loss)
    loss_values.append(batch_loss)

print(np.mean(loss_values))

0.8849826388856836
